name: Quick Build Test

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  quick_test:
    name: Quick build test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install numpy build
    
    - name: Test pure Python build
      env:
        PYROXA_PURE_PYTHON: "1"
      run: |
        echo "Building PyroXa in pure Python mode..."
        python -m build --wheel --outdir dist/
        echo "Build completed, testing wheel..."
    
    - name: Install and test wheel
      run: |
        pip install dist/*.whl
        python -c "import pyroxa; print(f'✅ PyroXa {pyroxa.get_version()} works!')"
        python -c "import pyroxa; print(f'Available functions: {len([x for x in dir(pyroxa) if not x.startswith(\"_\")])}')"
    
    - name: Test key functions
      run: |
        python -c "
        import pyroxa
        # Test key functions
        rate = pyroxa.autocatalytic_rate(0.1, 2.0, 1.5)
        print(f'autocatalytic_rate: {rate}')
        
        arr_rate = pyroxa.arrhenius_rate(1e6, 50000, 298)
        print(f'arrhenius_rate: {arr_rate}')
        
        interp = pyroxa.linear_interpolate(2.5, [1,2,3,4], [2,4,6,8])
        print(f'linear_interpolate: {interp}')
        
        print('✅ All function tests passed!')
        "
